server:
  port: 8888
spring:
  application:
    name: adventureworks-configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/soabel/bootcamp-adventureworks-configserver/tree/main/src/main/resources/git-localconfig-repo